add Android.mk to compile with aosp
as not debuggable application

Some notes:

1. LOCAL_SDK_VERSION
    when LOCAL_SDK_VERSION := 26 instead of current,
    following error would be reported:
    out/soong/.intermediates/prebuilts/sdk/current/support/android-support-v7-appcompat-nodeps/android_common/aar/res/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
    out/soong/.intermediates/prebuilts/sdk/current/support/android-support-v7-appcompat-nodeps/android_common/aar/res/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
    out/soong/.intermediates/prebuilts/sdk/current/support/android-support-compat-nodeps/android_common/aar/res/values/values.xml:79: error: resource android:attr/fontVariationSettings not found.
    out/soong/.intermediates/prebuilts/sdk/current/support/android-support-compat-nodeps/android_common/aar/res/values/values.xml:80: error: resource android:attr/ttcIndex not found.
    error: failed linking references.

2. LOCAL_USE_AAPT2 := true
    If we do not have it sepcified, following error would be reported:
    packages/apps/adb-join-wifi/res/values/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
    packages/apps/adb-join-wifi/res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.
    packages/apps/adb-join-wifi/res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
    packages/apps/adb-join-wifi/res/values/styles.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>